name       : mbedtls
version    : 2.28.1
release    : 10
source     :
    - https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.28.1.tar.gz : 82ff5fda18ecbdee9053bdbeed6059c89e487f3024227131657d4c4536735ed1
license    : GPL-2.0-or-later
component  : programming.library
summary    : Flexible SSL library.
description: |
    Portable, easy to use, readable and flexible SSL library.
setup      : |
    %cmake -DENABLE_PROGRAMS=OFF \
           -DENABLE_ZLIB_SUPPORT=ON \
           -DLIB_INSTALL_DIR=lib64 \
           -DUSE_SHARED_MBEDTLS_LIBRARY=ON \
           -DUSE_STATIC_MBEDTLS_LIBRARY=OFF .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
