name       : mbedtls
version    : 2.7.6
release    : 5
source     :
    - https://tls.mbed.org/download/mbedtls-2.7.6-gpl.tgz : 8036f9e392ad5d43e982ebd9508e7a62264fa858e3418adb844752969e580abf
license    : GPL-2.0-or-later
component  : programming.library
summary    : Flexible SSL library.
description: |
    Portable, easy to use, readable and flexible SSL library.
setup      : |
    %cmake -DENABLE_PROGRAMS=OFF \
           -DENABLE_ZLIB_SUPPORT=ON \
           -DLIB_INSTALL_DIR=lib64 \
           -DUSE_SHARED_MBEDTLS_LIBRARY=ON \
           -DUSE_STATIC_MBEDTLS_LIBRARY=OFF .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
