name       : mbedtls
version    : 2.28.3
release    : 12
source     :
    - https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.28.3.tar.gz : 1a21008fc93e7bdce2cb40a8f2d7c7b4034d9160035382c29cf91af8f96f2cd9
license    : GPL-2.0-or-later
component  : programming.library
summary    : Flexible SSL library.
description: |
    Portable, easy to use, readable and flexible SSL library.
setup      : |
    %cmake -DENABLE_PROGRAMS=OFF \
           -DENABLE_ZLIB_SUPPORT=ON \
           -DLIB_INSTALL_DIR=lib64 \
           -DUSE_SHARED_MBEDTLS_LIBRARY=ON \
           -DUSE_STATIC_MBEDTLS_LIBRARY=OFF .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
