name       : mbedtls
version    : 2.4.2
release    : 2
source     :
    - https://tls.mbed.org/download/mbedtls-2.4.2-gpl.tgz : d01f2d5586a52055329d194d909103f445bd2d0b6b2b5f1c830fbf828ac6299f
license    : GPL-2.0
component  : programming
summary    : Flexible SSL library.
description: |
    Portable, easy to use, readable and flexible SSL library.
setup      : |
    %cmake -DENABLE_PROGRAMS=OFF \
           -DENABLE_ZLIB_SUPPORT=ON \
           -DLIB_INSTALL_DIR=lib64 \
           -DUSE_SHARED_MBEDTLS_LIBRARY=ON \
           -DUSE_STATIC_MBEDTLS_LIBRARY=OFF .
build      : |
    %make
install    : |
    %make_install
