name       : mbedtls
version    : 2.7.6
release    : 6
source     :
    - https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.7.6.tar.gz : fb7d927dc4a064fc5ba9bcd9c77cf0ba83d23ee05c5c7d34238dbc058d6dbf05
license    : GPL-2.0-or-later
component  : programming.library
summary    : Flexible SSL library.
description: |
    Portable, easy to use, readable and flexible SSL library.
setup      : |
    %cmake -DENABLE_PROGRAMS=OFF \
           -DENABLE_ZLIB_SUPPORT=ON \
           -DLIB_INSTALL_DIR=lib64 \
           -DUSE_SHARED_MBEDTLS_LIBRARY=ON \
           -DUSE_STATIC_MBEDTLS_LIBRARY=OFF .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
