name       : mbedtls
version    : 2.3.0
release    : 1
source     :
    - https://tls.mbed.org/download/mbedtls-2.3.0-gpl.tgz : 21237014f779bde70b2d71399cc1ea53365eb7f10cdd74a13ee6329a1910cb49
license    : GPL-2.0
component  : programming
summary    : Flexible SSL library.
description: |
    Portable, easy to use, readable and flexible SSL library.
setup      : |
    #Borrowed from Gentoo
    %patch -p1 < $pkgfiles/mbedtls-2.3.0-include-guards.patch
    %patch -p1 < $pkgfiles/mbedtls-2.3.0-move-to-header.patch
    %patch -p1 < $pkgfiles/mbedtls-2.3.0-tests.patch

    %cmake -DENABLE_PROGRAMS=OFF \
           -DENABLE_ZLIB_SUPPORT=ON \
           -DLIB_INSTALL_DIR=lib64 \
           -DUSE_SHARED_MBEDTLS_LIBRARY=ON \
           -DUSE_STATIC_MBEDTLS_LIBRARY=OFF .
build      : |
    %make
install    : |
    %make_install
