name       : mbedtls
version    : 2.6.0
release    : 3
source     :
    - https://tls.mbed.org/download/mbedtls-2.6.0-gpl.tgz : a99959d7360def22f9108d2d487c9de384fe76c349697176b1f22370080d5810
license    : GPL-2.0
component  : programming.library
summary    : Flexible SSL library.
description: |
    Portable, easy to use, readable and flexible SSL library.
setup      : |
    %cmake -DENABLE_PROGRAMS=OFF \
           -DENABLE_ZLIB_SUPPORT=ON \
           -DLIB_INSTALL_DIR=lib64 \
           -DUSE_SHARED_MBEDTLS_LIBRARY=ON \
           -DUSE_STATIC_MBEDTLS_LIBRARY=OFF .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
